### ISSUE TITLE
Should we allow negative quantities

### ISSUE THREAD

**Issue by Luke1982** [Luke1982/IDLinesUX#1]
When we take this style of inventory lines into production, we could use it to keep stock effectively. That rases a question: should we allow negative quantities? Someone using a negative quantity to provide a 'discount' could increase the stock unintended this way.

**Comment by joebordes** [comment]
This use case can actually be done right now in the application and is incorrect.

I think I would make it work correctly now, or at least logically and then implement the same functionality with the new UI

**Comment by Luke1982** [comment]
I agree. Question is, how should we implement it? I remember you've created a validation business map, haven't used it yet so not sure if we could use it. Otherwise I could implement it into a pre-save validation. Maybe we should establish how we'd like to be able to edit and save records first.
