### ISSUE TITLE
How to style the field widths

### ISSUE THREAD

**Issue by Luke1982** [Luke1982/IDLinesUX#2]
What unit to use on the field widths? Taking into account that a flex grid is being used.

**Comment by joebordes** [comment]
I'd use percentage

https://stackoverflow.com/questions/609517/why-em-instead-of-px

**Comment by Luke1982** [comment]
I agree. Will take this into the next round.

**Comment by Luke1982** [comment]
Implemented LDS, that takes care of the width issues.
