### ISSUE TITLE
Shouldn't use number type inputs on currency fields

### ISSUE THREAD

**Issue by Luke1982** [Luke1982/IDLinesUX#3]
They will not accept a european style formatted currency

**Comment by joebordes** [comment]
I totally agree. I have been bit by this one recently.

**Comment by Luke1982** [comment]
Great. Let me think of a way to implement this.

**Comment by Luke1982** [comment]
Fixed. We still need to sanitize to user format and back to DB format when implementing but that is out of the scope of this repo.
