### ISSUE TITLE
Buttons for add new line and expand/collapse look the same

### ISSUE THREAD

**Issue by Luke1982** [Luke1982/IDLinesUX#5]
The button to add a new line looks the same as the one to expand a line. Should find a new icon for adding a new line.

**Comment by joebordes** [comment]
I would suggest using LDS icons: expand_all, colapse_all, expand, add

**Comment by Luke1982** [comment]
Yes, no problem but I'm not sure how much of LDS we have implemented. Last time I checked we had kind of a 'hacked' version.

**Comment by joebordes** [comment]
go for it: I want to make LDS work in coreBOS this year

**Comment by Luke1982** [comment]
Cool, let me see if I can get a branch up that does full LDS

**Comment by Luke1982** [comment]
Fixed by implementing LDS
