### ISSUE TITLE
Why not use LDS?

### ISSUE THREAD

**Issue by joebordes** [Luke1982/IDLinesUX#9]

**Comment by Luke1982** [comment]
Since I'm not sure which LDS components we have in place. Do we have full LDS component support?

**Comment by joebordes** [comment]
no, we don't, but we can and most probably will have it at some point in the near future, so you can count on having it

I like the idea of a cbds- CSS class. I was thinking of using LDS and adding the same class names with the cbds prefix, that way, we can override any CSS inherited from LDS.

Something like this:

```
<span class="slds-badge cbds-badge">I am Badge</span>
```

**Comment by Luke1982** [comment]
Personally I think we need some work to update Smarty files to ditch the table layout we have now if we use LDS, but I think that is less work than it seems. I like the idea of a cbds override. Just a matter of CSS file inclusion order. We could totally do that, would be more framework independant as well.
